### ISSUE TITLE
Login False

### ISSUE THREAD

**Issue by lucasub** [Frollamma/subito.it-API#2]
I try to login with my username and password but response is False
Login response: {"status":403,"info":"Forbidden","payload":{"status":"Forbidden","errors":[{"error_code":"AUTH:reject-status","info":"Login blocked"}] Code 403.

To login is neccessary to make request to SUBITO.IT for API enablement?
On Subito.it I didn't find any information about using the API.

Thank you fro answer.
Bye
Luca

**Comment by Frollamma** [comment]
Hi. I'm not maintaining this project anymore, any contribution is welcome, or just fork it.
I think the problem is that Subito is blocking our requests because it detects that are done programmatically. Subito doesn't have a public API, this small "library" I created is an unofficial API of Subito created by reverse engineering, so it's expected that Subito has some protections you have to try to bypass

**Comment by lucasub** [comment]
Thank you very much.
Bye
Luca
